### PR TITLE
alternate theme

### PR DESCRIPTION
**Pull request by abeyer**
A potential option for #3 

I'm not strongly in favor of any particular theme, but alabaster is a bit buggy on mobile, so anything else would likely be an improvement. I played with a couple and this seems nice and simple.

### CODE REVIEW

**Comment by abeyer** [comment]
ugh, I love travis 🙄 

One thing to note is that this doesn't support the github banner widget...probably not a big deal since we have a whole paragraph about contributing at the top of the page.

**Comment by Mariatta** [comment]
Looks great!! Preview is here: https://deploy-preview-16--relaxed-lalande-396fdc.netlify.com/

**Comment by Mariatta** [comment]
Thanks @abeyer, the new theme looks really great!
We have a new logo (as of few days ago), will you be able to update with the new logo? It can be seen in our main website. 
Once we have new logo I can merge this.
Thanks!

**Comment by Mariatta** [comment]
Something that just occurred to me is, while the new theme looks great, I'm a little uncomfortable that it doesn't support readthedocs' ethical advertising (available in alabaster, rtd's sphinx theme, and mkdocs). My personal recommendation is not switching to another theme unless we (pycascades) can support readthedocs some other way.

**Comment by ndenny** [comment]
After @abeyer 's kind donation, I guess this is good to go?

**Comment by Mariatta** [comment]
Yup. We need a new logo but I can do it in the next PR.
Thanks so much @abeyer!

**Pull request merged**
