### PR TITLE
Update lightning talk info with info from Slack channel

### PR DESCRIPTION
**Pull request by lorenanicole**
Added in notes to mirror the statement from Slack #lightningtalks channel on how submission will work. 

Question: Are lightning talks going to be recorded? If so I think that's worth putting in the welcome wagon so folks know what to expect.

### CODE REVIEW

**Comment by Mariatta** [comment]
Thanks @lorenanicole! We can record the lightning talks, but perhaps we should first get consent.

Should we add a note about "lightning talks will be recorded, if you do not wish to be recorded, let us know?" Or should it be the other way around? (talks are not recorded, let us know if you want to be recorded) 🤔

**Comment by lorenanicole** [comment]
Working this topic out now with Alan on Slack @Mariatta !

**Comment by lorenanicole** [comment]
@Mariatta updated with Alan feedback!

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
Thanks!

**Pull request merged**
