### PR TITLE
Saturday lightning talks

### PR DESCRIPTION
**Pull request by abeyer**
not ready for merge yet

### CODE REVIEW

**Comment by abeyer** [comment]
I dunno why the netlify stuff is broken, if someone knows how to fix it, feel free.

**Review by ndenny — COMMENTED** [review]
I think you're missing the _ at the end of the links:  ``
```text 
  `Text <url>`_
```

**Comment by Mariatta** [comment]
@abeyer I've removed the lightning talk that needed to be removed.

**Comment by abeyer** [comment]
I thought this was good now but links are screwed up and one had permissions locked down...

**Review by Mariatta — APPROVED** [review]

**Comment by Mariatta** [comment]
I think this looks great now. Thanks @abeyer. I just checked the links on netlify, seems great. If there is any issues we can always have another PR. Thank you!!

**Pull request merged**
